server:
  port: 8766


mock:
  mockData:
    #uri: return data
    #对于特殊字符，key需要使用"[key]"的形式，value需要使用'value'的形式
    "[/chain/get_account]": '{"account_name":"eosio","head_block_num":684186,"head_block_time":"2020-11-10T15:32:37.000","privileged":true,"last_code_update":"1970-01-01T00:00:00.000","created":"2018-06-01T12:00:00.000","ram_quota":-1,"net_weight":-1,"cpu_weight":-1,"net_limit":{"used":-1,"available":-1,"max":-1},"cpu_limit":{"used":-1,"available":-1,"max":-1},"ram_usage":3076,"permissions":[{"perm_name":"active","parent":"owner","required_auth":{"threshold":1,"keys":[{"key":"EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","weight":1}],"accounts":[],"waits":[]}},{"perm_name":"owner","parent":"","required_auth":{"threshold":1,"keys":[{"key":"EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","weight":1}],"accounts":[],"waits":[]}}],"total_resources":null,"self_delegated_bandwidth":null,"refund_request":null,"voter_info":null}'
    "[/api/v0/token/authorize]": eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxMDAxIiwic3ViIjoi5bCP6IuNIiwiaWF0IjoxNjAzNjIyNTIwLCJleHAiOjE2MDM2MjYxMjAsInJvbGVzIjoiYWRtaW4ifQ.rsFD3V0GOAXAsvobiYe_UI7EO7jeif6npZZFOmKd2X8
    "[/api/v0/object/put]": '{"hash":"ZGEwMWU4M2IxNDY2OWFlOWM3YjI5NmQ4Nzk5YTcwMGM4NzM2ODllNTVhMWVmODEwMGRhZTJhZDVmYzc0YjNmNA"}'